# Enable PS/2 mouse driver on peripheral side
# Our Kconfig bypasses the `depends on (!ZMK_SPLIT || ZMK_SPLIT_ROLE_CENTRAL)` restriction
# by providing CONFIG_ZMK_INPUT_MOUSE_PS2_PERIPHERAL
CONFIG_ZMK_INPUT_MOUSE_PS2_PERIPHERAL=y
